set(CMAKE_C_ARCHIVE_CREATE   "<CMAKE_AR> /out:<TARGET> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> /out:<TARGET> <OBJECTS>")
set(CMAKE_C_ARCHIVE_APPEND "<CMAKE_AR> /out:<TARGET> <TARGET> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_APPEND "<CMAKE_AR> /out:<TARGET> <TARGET> <OBJECTS>")
set(CMAKE_C_ARCHIVE_FINISH   "")
set(CMAKE_CXX_ARCHIVE_FINISH "")

set(CMAKE_C_STANDARD_LIBRARIES   "" CACHE STRING "" FORCE)
set(CMAKE_CXX_STANDARD_LIBRARIES "" CACHE STRING "" FORCE)

set(CMAKE_C_IMPLICIT_LINK_LIBRARIES   "")
set(CMAKE_CXX_IMPLICIT_LINK_LIBRARIES "")
set(CMAKE_C_IMPLICIT_LINK_DIRECTORIES "")
set(CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES "")

set(CMAKE_C_LINKER_WRAPPER_FLAG   "")
set(CMAKE_C_LINKER_WRAPPER_FLAG_SEP "")
set(CMAKE_CXX_LINKER_WRAPPER_FLAG "")
set(CMAKE_CXX_LINKER_WRAPPER_FLAG_SEP "")

set(CMAKE_EXECUTABLE_SUFFIX ".efi")

set(CMAKE_EXE_LINKER_FLAGS_INIT "")

set(CMAKE_C_CREATE_CONSOLE_EXE "")
set(CMAKE_CXX_CREATE_CONSOLE_EXE "")

set(CMAKE_C_LINK_EXECUTABLE
    "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> -out:<TARGET>")
set(CMAKE_CXX_LINK_EXECUTABLE
    "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> -out:<TARGET>")

